bot:
  token: "123456789:abcdefghijklmnopqrstuvwxyz"          # 替换为你的 Bot Token
  target_chat_id: -1001265283025        # 你需要监控的群组的ID (通常以 -100 开头)
  admin_ids:                            # 允许使用bot的 ID 列表
    - 123456789
    - 987654321
# 如果你是话题群组，请自己写好分区ID所对应的分区名，并删除“#”，TG没给bot获取这个字段的权限，其中的「1: "默认"」不要改
#  topic_mapping:                        
#    1: "默认"
#    1111: "日常闲聊区"
#    2222: "每日签到区"


database:
  db_dir: ""                        # 数据库存放位置，绝对路径比如："/mybot_data/db"，不填，则默认存在项目根目录下
  buffer_limit: 50                  # 缓冲池达到多少条时触发写入
  flush_interval_seconds: 5         # 即使没缓冲池，每隔几秒也强制写入一次
  max_text_length: 4096             # TG 原生最大长度（除非你知道在做什么，否则别改这个）
  display_text_length: 2000         # 搜索显示时单消息截断长度（除非你知道在做什么，否则别改这个）